linters:
  enable:
    - deadcode
    - errcheck
    - goconst
    - gofmt
    - golint
    - gosec
    - govet
    - ineffassign
    - interfacer
    - lll
    - megacheck
    - misspell
    - nakedret
    - structcheck
    - revive
    - unconvert
    - unused
    - varcheck
  enable-all: false
run:
  skip-files:
    - schema.go
    - pulumiManifest.go
  timeout: 20m
