// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export class NetworkRoute extends pulumi.CustomResource {
    /**
     * Get an existing NetworkRoute resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: NetworkRouteState, opts?: pulumi.CustomResourceOptions): NetworkRoute {
        return new NetworkRoute(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'stackpath:compute/networkRoute:NetworkRoute';

    /**
     * Returns true if the given object is an instance of NetworkRoute.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is NetworkRoute {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === NetworkRoute.__pulumiType;
    }

    public readonly annotations!: pulumi.Output<{[key: string]: string} | undefined>;
    public readonly destinationPrefixes!: pulumi.Output<string[]>;
    public readonly gatewaySelectors!: pulumi.Output<outputs.compute.NetworkRouteGatewaySelector[] | undefined>;
    public readonly labels!: pulumi.Output<{[key: string]: string} | undefined>;
    public readonly name!: pulumi.Output<string>;
    public readonly networkId!: pulumi.Output<string>;
    public readonly slug!: pulumi.Output<string>;
    public /*out*/ readonly version!: pulumi.Output<string>;

    /**
     * Create a NetworkRoute resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: NetworkRouteArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: NetworkRouteArgs | NetworkRouteState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as NetworkRouteState | undefined;
            resourceInputs["annotations"] = state ? state.annotations : undefined;
            resourceInputs["destinationPrefixes"] = state ? state.destinationPrefixes : undefined;
            resourceInputs["gatewaySelectors"] = state ? state.gatewaySelectors : undefined;
            resourceInputs["labels"] = state ? state.labels : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["networkId"] = state ? state.networkId : undefined;
            resourceInputs["slug"] = state ? state.slug : undefined;
            resourceInputs["version"] = state ? state.version : undefined;
        } else {
            const args = argsOrState as NetworkRouteArgs | undefined;
            if ((!args || args.destinationPrefixes === undefined) && !opts.urn) {
                throw new Error("Missing required property 'destinationPrefixes'");
            }
            if ((!args || args.networkId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'networkId'");
            }
            resourceInputs["annotations"] = args ? args.annotations : undefined;
            resourceInputs["destinationPrefixes"] = args ? args.destinationPrefixes : undefined;
            resourceInputs["gatewaySelectors"] = args ? args.gatewaySelectors : undefined;
            resourceInputs["labels"] = args ? args.labels : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["networkId"] = args ? args.networkId : undefined;
            resourceInputs["slug"] = args ? args.slug : undefined;
            resourceInputs["version"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(NetworkRoute.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering NetworkRoute resources.
 */
export interface NetworkRouteState {
    annotations?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    destinationPrefixes?: pulumi.Input<pulumi.Input<string>[]>;
    gatewaySelectors?: pulumi.Input<pulumi.Input<inputs.compute.NetworkRouteGatewaySelector>[]>;
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    name?: pulumi.Input<string>;
    networkId?: pulumi.Input<string>;
    slug?: pulumi.Input<string>;
    version?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a NetworkRoute resource.
 */
export interface NetworkRouteArgs {
    annotations?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    destinationPrefixes: pulumi.Input<pulumi.Input<string>[]>;
    gatewaySelectors?: pulumi.Input<pulumi.Input<inputs.compute.NetworkRouteGatewaySelector>[]>;
    labels?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    name?: pulumi.Input<string>;
    networkId: pulumi.Input<string>;
    slug?: pulumi.Input<string>;
}
