// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
	"github.com/stackpath/pulumi-stackpath/sdk/go/stackpath/internal"
)

var _ = internal.GetEnvOrDefault

func GetAccessToken(ctx *pulumi.Context) string {
	return config.Get(ctx, "stackpath:accessToken")
}
func GetBaseUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "stackpath:baseUrl")
}
func GetClientId(ctx *pulumi.Context) string {
	return config.Get(ctx, "stackpath:clientId")
}
func GetClientSecret(ctx *pulumi.Context) string {
	return config.Get(ctx, "stackpath:clientSecret")
}
func GetStackId(ctx *pulumi.Context) string {
	return config.Get(ctx, "stackpath:stackId")
}
