// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Stackpath.Stackpath.Compute.Outputs
{

    [OutputType]
    public sealed class NetworkPolicyIngress
    {
        public readonly string Action;
        public readonly string? Description;
        public readonly Outputs.NetworkPolicyIngressFrom? From;
        public readonly Outputs.NetworkPolicyIngressProtocol? Protocol;

        [OutputConstructor]
        private NetworkPolicyIngress(
            string action,

            string? description,

            Outputs.NetworkPolicyIngressFrom? from,

            Outputs.NetworkPolicyIngressProtocol? protocol)
        {
            Action = action;
            Description = description;
            From = from;
            Protocol = protocol;
        }
    }
}
