// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackpath.Compute.Outputs
{

    [OutputType]
    public sealed class NetworkPolicyEgressToIpBlock
    {
        public readonly string Cidr;
        public readonly ImmutableArray<string> Excepts;

        [OutputConstructor]
        private NetworkPolicyEgressToIpBlock(
            string cidr,

            ImmutableArray<string> excepts)
        {
            Cidr = cidr;
            Excepts = excepts;
        }
    }
}
