// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Stackpath.Stackpath.Compute.Outputs
{

    [OutputType]
    public sealed class NetworkPolicyIngressFrom
    {
        public readonly ImmutableArray<Outputs.NetworkPolicyIngressFromInstanceSelector> InstanceSelectors;
        public readonly ImmutableArray<Outputs.NetworkPolicyIngressFromIpBlock> IpBlocks;
        public readonly ImmutableArray<Outputs.NetworkPolicyIngressFromNetworkSelector> NetworkSelectors;

        [OutputConstructor]
        private NetworkPolicyIngressFrom(
            ImmutableArray<Outputs.NetworkPolicyIngressFromInstanceSelector> instanceSelectors,

            ImmutableArray<Outputs.NetworkPolicyIngressFromIpBlock> ipBlocks,

            ImmutableArray<Outputs.NetworkPolicyIngressFromNetworkSelector> networkSelectors)
        {
            InstanceSelectors = instanceSelectors;
            IpBlocks = ipBlocks;
            NetworkSelectors = networkSelectors;
        }
    }
}
