// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackpath.Compute.Outputs
{

    [OutputType]
    public sealed class NetworkPolicyEgressProtocol
    {
        public readonly Outputs.NetworkPolicyEgressProtocolAh? Ah;
        public readonly Outputs.NetworkPolicyEgressProtocolEsp? Esp;
        public readonly Outputs.NetworkPolicyEgressProtocolGre? Gre;
        public readonly Outputs.NetworkPolicyEgressProtocolIcmp? Icmp;
        public readonly Outputs.NetworkPolicyEgressProtocolTcp? Tcp;
        public readonly Outputs.NetworkPolicyEgressProtocolTcpUdp? TcpUdp;
        public readonly Outputs.NetworkPolicyEgressProtocolUdp? Udp;

        [OutputConstructor]
        private NetworkPolicyEgressProtocol(
            Outputs.NetworkPolicyEgressProtocolAh? ah,

            Outputs.NetworkPolicyEgressProtocolEsp? esp,

            Outputs.NetworkPolicyEgressProtocolGre? gre,

            Outputs.NetworkPolicyEgressProtocolIcmp? icmp,

            Outputs.NetworkPolicyEgressProtocolTcp? tcp,

            Outputs.NetworkPolicyEgressProtocolTcpUdp? tcpUdp,

            Outputs.NetworkPolicyEgressProtocolUdp? udp)
        {
            Ah = ah;
            Esp = esp;
            Gre = gre;
            Icmp = icmp;
            Tcp = tcp;
            TcpUdp = tcpUdp;
            Udp = udp;
        }
    }
}
