// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Stackpath.Stackpath.Compute.Outputs
{

    [OutputType]
    public sealed class WorkloadContainerRuntimeEnvironmentSecurityContext
    {
        public readonly string? RunAsGroup;
        public readonly bool? RunAsNonRoot;
        public readonly string? RunAsUser;
        public readonly ImmutableArray<string> SupplementalGroups;
        public readonly ImmutableDictionary<string, string>? Sysctl;

        [OutputConstructor]
        private WorkloadContainerRuntimeEnvironmentSecurityContext(
            string? runAsGroup,

            bool? runAsNonRoot,

            string? runAsUser,

            ImmutableArray<string> supplementalGroups,

            ImmutableDictionary<string, string>? sysctl)
        {
            RunAsGroup = runAsGroup;
            RunAsNonRoot = runAsNonRoot;
            RunAsUser = runAsUser;
            SupplementalGroups = supplementalGroups;
            Sysctl = sysctl;
        }
    }
}
