// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Stackpath.Stackpath.Compute.Outputs
{

    [OutputType]
    public sealed class WorkloadNetworkInterface
    {
        public readonly bool? EnableOneToOneNat;
        public readonly ImmutableArray<string> IpFamilies;
        public readonly string? Ipv6Subnet;
        public readonly string Network;
        public readonly string? Subnet;

        [OutputConstructor]
        private WorkloadNetworkInterface(
            bool? enableOneToOneNat,

            ImmutableArray<string> ipFamilies,

            string? ipv6Subnet,

            string network,

            string? subnet)
        {
            EnableOneToOneNat = enableOneToOneNat;
            IpFamilies = ipFamilies;
            Ipv6Subnet = ipv6Subnet;
            Network = network;
            Subnet = subnet;
        }
    }
}
