// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Stackpath.Stackpath.Compute.Outputs
{

    [OutputType]
    public sealed class WorkloadVirtualMachineRuntimeEnvironmentDns
    {
        public readonly ImmutableArray<Outputs.WorkloadVirtualMachineRuntimeEnvironmentDnsHostAlias> HostAliases;
        public readonly ImmutableArray<Outputs.WorkloadVirtualMachineRuntimeEnvironmentDnsResolverConfig> ResolverConfigs;

        [OutputConstructor]
        private WorkloadVirtualMachineRuntimeEnvironmentDns(
            ImmutableArray<Outputs.WorkloadVirtualMachineRuntimeEnvironmentDnsHostAlias> hostAliases,

            ImmutableArray<Outputs.WorkloadVirtualMachineRuntimeEnvironmentDnsResolverConfig> resolverConfigs)
        {
            HostAliases = hostAliases;
            ResolverConfigs = resolverConfigs;
        }
    }
}
