// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Stackpath.Stackpath.Compute.Outputs
{

    [OutputType]
    public sealed class WorkloadContainerRuntimeEnvironmentDnsResolverConfig
    {
        public readonly ImmutableArray<string> Nameservers;
        public readonly ImmutableDictionary<string, object>? Options;
        public readonly ImmutableArray<string> Searches;

        [OutputConstructor]
        private WorkloadContainerRuntimeEnvironmentDnsResolverConfig(
            ImmutableArray<string> nameservers,

            ImmutableDictionary<string, object>? options,

            ImmutableArray<string> searches)
        {
            Nameservers = nameservers;
            Options = options;
            Searches = searches;
        }
    }
}
