// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Stackpath.Stackpath.Compute.Outputs
{

    [OutputType]
    public sealed class WorkloadInstanceInitContainer
    {
        public readonly ImmutableArray<string> Commands;
        public readonly ImmutableArray<Outputs.WorkloadInstanceInitContainerEnv> Envs;
        public readonly string Image;
        public readonly Outputs.WorkloadInstanceInitContainerLivenessProbe? LivenessProbe;
        public readonly string Name;
        public readonly ImmutableArray<Outputs.WorkloadInstanceInitContainerPort> Ports;
        public readonly Outputs.WorkloadInstanceInitContainerReadinessProbe? ReadinessProbe;
        public readonly Outputs.WorkloadInstanceInitContainerResources Resources;
        public readonly Outputs.WorkloadInstanceInitContainerSecurityContext? SecurityContext;
        public readonly ImmutableArray<Outputs.WorkloadInstanceInitContainerVolumeMount> VolumeMounts;

        [OutputConstructor]
        private WorkloadInstanceInitContainer(
            ImmutableArray<string> commands,

            ImmutableArray<Outputs.WorkloadInstanceInitContainerEnv> envs,

            string image,

            Outputs.WorkloadInstanceInitContainerLivenessProbe? livenessProbe,

            string name,

            ImmutableArray<Outputs.WorkloadInstanceInitContainerPort> ports,

            Outputs.WorkloadInstanceInitContainerReadinessProbe? readinessProbe,

            Outputs.WorkloadInstanceInitContainerResources resources,

            Outputs.WorkloadInstanceInitContainerSecurityContext? securityContext,

            ImmutableArray<Outputs.WorkloadInstanceInitContainerVolumeMount> volumeMounts)
        {
            Commands = commands;
            Envs = envs;
            Image = image;
            LivenessProbe = livenessProbe;
            Name = name;
            Ports = ports;
            ReadinessProbe = readinessProbe;
            Resources = resources;
            SecurityContext = securityContext;
            VolumeMounts = volumeMounts;
        }
    }
}
