// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Stackpath.Stackpath.Compute.Outputs
{

    [OutputType]
    public sealed class WorkloadContainerRuntimeEnvironment
    {
        public readonly Outputs.WorkloadContainerRuntimeEnvironmentDns Dns;
        public readonly Outputs.WorkloadContainerRuntimeEnvironmentSecurityContext? SecurityContext;
        public readonly bool? ShareProcessNamespace;
        public readonly int? TerminationGracePeriodSeconds;

        [OutputConstructor]
        private WorkloadContainerRuntimeEnvironment(
            Outputs.WorkloadContainerRuntimeEnvironmentDns dns,

            Outputs.WorkloadContainerRuntimeEnvironmentSecurityContext? securityContext,

            bool? shareProcessNamespace,

            int? terminationGracePeriodSeconds)
        {
            Dns = dns;
            SecurityContext = securityContext;
            ShareProcessNamespace = shareProcessNamespace;
            TerminationGracePeriodSeconds = terminationGracePeriodSeconds;
        }
    }
}
