// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Stackpath.Stackpath.Compute.Outputs
{

    [OutputType]
    public sealed class WorkloadContainerEnv
    {
        public readonly string Key;
        public readonly string? SecretValue;
        public readonly string? Value;
        public readonly Outputs.WorkloadContainerEnvValueFrom? ValueFrom;

        [OutputConstructor]
        private WorkloadContainerEnv(
            string key,

            string? secretValue,

            string? value,

            Outputs.WorkloadContainerEnvValueFrom? valueFrom)
        {
            Key = key;
            SecretValue = secretValue;
            Value = value;
            ValueFrom = valueFrom;
        }
    }
}
