// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Stackpath.Stackpath.Compute.Outputs
{

    [OutputType]
    public sealed class WorkloadContainer
    {
        public readonly ImmutableArray<string> Commands;
        public readonly ImmutableArray<Outputs.WorkloadContainerEnv> Envs;
        public readonly string Image;
        public readonly Outputs.WorkloadContainerLivenessProbe? LivenessProbe;
        public readonly string Name;
        public readonly ImmutableArray<Outputs.WorkloadContainerPort> Ports;
        public readonly Outputs.WorkloadContainerReadinessProbe? ReadinessProbe;
        public readonly Outputs.WorkloadContainerResources Resources;
        public readonly Outputs.WorkloadContainerSecurityContext? SecurityContext;
        public readonly ImmutableArray<Outputs.WorkloadContainerVolumeMount> VolumeMounts;

        [OutputConstructor]
        private WorkloadContainer(
            ImmutableArray<string> commands,

            ImmutableArray<Outputs.WorkloadContainerEnv> envs,

            string image,

            Outputs.WorkloadContainerLivenessProbe? livenessProbe,

            string name,

            ImmutableArray<Outputs.WorkloadContainerPort> ports,

            Outputs.WorkloadContainerReadinessProbe? readinessProbe,

            Outputs.WorkloadContainerResources resources,

            Outputs.WorkloadContainerSecurityContext? securityContext,

            ImmutableArray<Outputs.WorkloadContainerVolumeMount> volumeMounts)
        {
            Commands = commands;
            Envs = envs;
            Image = image;
            LivenessProbe = livenessProbe;
            Name = name;
            Ports = ports;
            ReadinessProbe = readinessProbe;
            Resources = resources;
            SecurityContext = securityContext;
            VolumeMounts = volumeMounts;
        }
    }
}
