// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Stackpath.Stackpath.Compute.Outputs
{

    [OutputType]
    public sealed class WorkloadImagePullCredentialDockerRegistry
    {
        public readonly string? Email;
        public readonly string Password;
        public readonly string? Server;
        public readonly string Username;

        [OutputConstructor]
        private WorkloadImagePullCredentialDockerRegistry(
            string? email,

            string password,

            string? server,

            string username)
        {
            Email = email;
            Password = password;
            Server = server;
            Username = username;
        }
    }
}
