// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Stackpath.Stackpath.Compute.Outputs
{

    [OutputType]
    public sealed class WorkloadInstanceInitContainerLivenessProbe
    {
        public readonly int FailureThreshold;
        public readonly Outputs.WorkloadInstanceInitContainerLivenessProbeHttpGet? HttpGet;
        public readonly int? InitialDelaySeconds;
        public readonly int? PeriodSeconds;
        public readonly int SuccessThreshold;
        public readonly Outputs.WorkloadInstanceInitContainerLivenessProbeTcpSocket? TcpSocket;
        public readonly int? TimeoutSeconds;

        [OutputConstructor]
        private WorkloadInstanceInitContainerLivenessProbe(
            int failureThreshold,

            Outputs.WorkloadInstanceInitContainerLivenessProbeHttpGet? httpGet,

            int? initialDelaySeconds,

            int? periodSeconds,

            int successThreshold,

            Outputs.WorkloadInstanceInitContainerLivenessProbeTcpSocket? tcpSocket,

            int? timeoutSeconds)
        {
            FailureThreshold = failureThreshold;
            HttpGet = httpGet;
            InitialDelaySeconds = initialDelaySeconds;
            PeriodSeconds = periodSeconds;
            SuccessThreshold = successThreshold;
            TcpSocket = tcpSocket;
            TimeoutSeconds = timeoutSeconds;
        }
    }
}
