// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Stackpath.Stackpath.Compute.Outputs
{

    [OutputType]
    public sealed class WorkloadVirtualMachine
    {
        public readonly string Image;
        public readonly Outputs.WorkloadVirtualMachineLivenessProbe? LivenessProbe;
        public readonly string Name;
        public readonly ImmutableArray<Outputs.WorkloadVirtualMachinePort> Ports;
        public readonly Outputs.WorkloadVirtualMachineReadinessProbe? ReadinessProbe;
        public readonly Outputs.WorkloadVirtualMachineResources Resources;
        public readonly string? UserData;
        public readonly ImmutableArray<Outputs.WorkloadVirtualMachineVolumeMount> VolumeMounts;

        [OutputConstructor]
        private WorkloadVirtualMachine(
            string image,

            Outputs.WorkloadVirtualMachineLivenessProbe? livenessProbe,

            string name,

            ImmutableArray<Outputs.WorkloadVirtualMachinePort> ports,

            Outputs.WorkloadVirtualMachineReadinessProbe? readinessProbe,

            Outputs.WorkloadVirtualMachineResources resources,

            string? userData,

            ImmutableArray<Outputs.WorkloadVirtualMachineVolumeMount> volumeMounts)
        {
            Image = image;
            LivenessProbe = livenessProbe;
            Name = name;
            Ports = ports;
            ReadinessProbe = readinessProbe;
            Resources = resources;
            UserData = userData;
            VolumeMounts = volumeMounts;
        }
    }
}
