// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Stackpath.Stackpath.Compute.Outputs
{

    [OutputType]
    public sealed class WorkloadInstanceNetworkInterface
    {
        public readonly string Gateway;
        public readonly string IpAddress;
        public readonly ImmutableArray<string> IpAddressAliases;
        public readonly string Ipv6Address;
        public readonly ImmutableArray<string> Ipv6AddressAliases;
        public readonly string Ipv6Gateway;
        public readonly string Network;

        [OutputConstructor]
        private WorkloadInstanceNetworkInterface(
            string gateway,

            string ipAddress,

            ImmutableArray<string> ipAddressAliases,

            string ipv6Address,

            ImmutableArray<string> ipv6AddressAliases,

            string ipv6Gateway,

            string network)
        {
            Gateway = gateway;
            IpAddress = ipAddress;
            IpAddressAliases = ipAddressAliases;
            Ipv6Address = ipv6Address;
            Ipv6AddressAliases = ipv6AddressAliases;
            Ipv6Gateway = ipv6Gateway;
            Network = network;
        }
    }
}
