// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackpath.Compute.Outputs
{

    [OutputType]
    public sealed class WorkloadTargetScaleSettingsMetric
    {
        public readonly int? AverageUtilization;
        public readonly string? AverageValue;
        public readonly string Metric;

        [OutputConstructor]
        private WorkloadTargetScaleSettingsMetric(
            int? averageUtilization,

            string? averageValue,

            string metric)
        {
            AverageUtilization = averageUtilization;
            AverageValue = averageValue;
            Metric = metric;
        }
    }
}
