// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Stackpath.Stackpath.Compute.Outputs
{

    [OutputType]
    public sealed class WorkloadTarget
    {
        public readonly string? DeploymentScope;
        public readonly int? MaxReplicas;
        public readonly int MinReplicas;
        public readonly string Name;
        public readonly Outputs.WorkloadTargetScaleSettings? ScaleSettings;
        public readonly ImmutableArray<Outputs.WorkloadTargetSelector> Selectors;

        [OutputConstructor]
        private WorkloadTarget(
            string? deploymentScope,

            int? maxReplicas,

            int minReplicas,

            string name,

            Outputs.WorkloadTargetScaleSettings? scaleSettings,

            ImmutableArray<Outputs.WorkloadTargetSelector> selectors)
        {
            DeploymentScope = deploymentScope;
            MaxReplicas = maxReplicas;
            MinReplicas = minReplicas;
            Name = name;
            ScaleSettings = scaleSettings;
            Selectors = selectors;
        }
    }
}
