// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackpath.Compute.Outputs
{

    [OutputType]
    public sealed class WorkloadInstanceVirtualMachineResources
    {
        public readonly ImmutableDictionary<string, string> Requests;

        [OutputConstructor]
        private WorkloadInstanceVirtualMachineResources(ImmutableDictionary<string, string> requests)
        {
            Requests = requests;
        }
    }
}
