// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Stackpath.Stackpath.Compute.Outputs
{

    [OutputType]
    public sealed class WorkloadInitContainerSecurityContext
    {
        public readonly bool? AllowPrivilegeEscalation;
        public readonly Outputs.WorkloadInitContainerSecurityContextCapabilities? Capabilities;
        public readonly bool? ReadOnlyRootFilesystem;
        public readonly string? RunAsGroup;
        public readonly bool? RunAsNonRoot;
        public readonly string? RunAsUser;

        [OutputConstructor]
        private WorkloadInitContainerSecurityContext(
            bool? allowPrivilegeEscalation,

            Outputs.WorkloadInitContainerSecurityContextCapabilities? capabilities,

            bool? readOnlyRootFilesystem,

            string? runAsGroup,

            bool? runAsNonRoot,

            string? runAsUser)
        {
            AllowPrivilegeEscalation = allowPrivilegeEscalation;
            Capabilities = capabilities;
            ReadOnlyRootFilesystem = readOnlyRootFilesystem;
            RunAsGroup = runAsGroup;
            RunAsNonRoot = runAsNonRoot;
            RunAsUser = runAsUser;
        }
    }
}
