// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Stackpath.Stackpath.Compute
{
    [StackpathResourceType("stackpath:compute/networkPolicy:NetworkPolicy")]
    public partial class NetworkPolicy : global::Pulumi.CustomResource
    {
        [Output("annotations")]
        public Output<ImmutableDictionary<string, string>?> Annotations { get; private set; } = null!;

        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        [Output("egresses")]
        public Output<ImmutableArray<Outputs.NetworkPolicyEgress>> Egresses { get; private set; } = null!;

        [Output("ingresses")]
        public Output<ImmutableArray<Outputs.NetworkPolicyIngress>> Ingresses { get; private set; } = null!;

        [Output("instanceSelectors")]
        public Output<ImmutableArray<Outputs.NetworkPolicyInstanceSelector>> InstanceSelectors { get; private set; } = null!;

        [Output("labels")]
        public Output<ImmutableDictionary<string, string>?> Labels { get; private set; } = null!;

        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        [Output("networkSelectors")]
        public Output<ImmutableArray<Outputs.NetworkPolicyNetworkSelector>> NetworkSelectors { get; private set; } = null!;

        [Output("policyTypes")]
        public Output<ImmutableArray<string>> PolicyTypes { get; private set; } = null!;

        [Output("priority")]
        public Output<int> Priority { get; private set; } = null!;

        [Output("slug")]
        public Output<string> Slug { get; private set; } = null!;

        [Output("version")]
        public Output<string> Version { get; private set; } = null!;


        /// <summary>
        /// Create a NetworkPolicy resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public NetworkPolicy(string name, NetworkPolicyArgs args, CustomResourceOptions? options = null)
            : base("stackpath:compute/networkPolicy:NetworkPolicy", name, args ?? new NetworkPolicyArgs(), MakeResourceOptions(options, ""))
        {
        }

        private NetworkPolicy(string name, Input<string> id, NetworkPolicyState? state = null, CustomResourceOptions? options = null)
            : base("stackpath:compute/networkPolicy:NetworkPolicy", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "https://github.com/stackpath/pulumi-stackpath/releases/download/v${VERSION}",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing NetworkPolicy resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static NetworkPolicy Get(string name, Input<string> id, NetworkPolicyState? state = null, CustomResourceOptions? options = null)
        {
            return new NetworkPolicy(name, id, state, options);
        }
    }

    public sealed class NetworkPolicyArgs : global::Pulumi.ResourceArgs
    {
        [Input("annotations")]
        private InputMap<string>? _annotations;
        public InputMap<string> Annotations
        {
            get => _annotations ?? (_annotations = new InputMap<string>());
            set => _annotations = value;
        }

        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("egresses")]
        private InputList<Inputs.NetworkPolicyEgressArgs>? _egresses;
        public InputList<Inputs.NetworkPolicyEgressArgs> Egresses
        {
            get => _egresses ?? (_egresses = new InputList<Inputs.NetworkPolicyEgressArgs>());
            set => _egresses = value;
        }

        [Input("ingresses")]
        private InputList<Inputs.NetworkPolicyIngressArgs>? _ingresses;
        public InputList<Inputs.NetworkPolicyIngressArgs> Ingresses
        {
            get => _ingresses ?? (_ingresses = new InputList<Inputs.NetworkPolicyIngressArgs>());
            set => _ingresses = value;
        }

        [Input("instanceSelectors")]
        private InputList<Inputs.NetworkPolicyInstanceSelectorArgs>? _instanceSelectors;
        public InputList<Inputs.NetworkPolicyInstanceSelectorArgs> InstanceSelectors
        {
            get => _instanceSelectors ?? (_instanceSelectors = new InputList<Inputs.NetworkPolicyInstanceSelectorArgs>());
            set => _instanceSelectors = value;
        }

        [Input("labels")]
        private InputMap<string>? _labels;
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("networkSelectors")]
        private InputList<Inputs.NetworkPolicyNetworkSelectorArgs>? _networkSelectors;
        public InputList<Inputs.NetworkPolicyNetworkSelectorArgs> NetworkSelectors
        {
            get => _networkSelectors ?? (_networkSelectors = new InputList<Inputs.NetworkPolicyNetworkSelectorArgs>());
            set => _networkSelectors = value;
        }

        [Input("policyTypes", required: true)]
        private InputList<string>? _policyTypes;
        public InputList<string> PolicyTypes
        {
            get => _policyTypes ?? (_policyTypes = new InputList<string>());
            set => _policyTypes = value;
        }

        [Input("priority", required: true)]
        public Input<int> Priority { get; set; } = null!;

        [Input("slug", required: true)]
        public Input<string> Slug { get; set; } = null!;

        public NetworkPolicyArgs()
        {
        }
        public static new NetworkPolicyArgs Empty => new NetworkPolicyArgs();
    }

    public sealed class NetworkPolicyState : global::Pulumi.ResourceArgs
    {
        [Input("annotations")]
        private InputMap<string>? _annotations;
        public InputMap<string> Annotations
        {
            get => _annotations ?? (_annotations = new InputMap<string>());
            set => _annotations = value;
        }

        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("egresses")]
        private InputList<Inputs.NetworkPolicyEgressGetArgs>? _egresses;
        public InputList<Inputs.NetworkPolicyEgressGetArgs> Egresses
        {
            get => _egresses ?? (_egresses = new InputList<Inputs.NetworkPolicyEgressGetArgs>());
            set => _egresses = value;
        }

        [Input("ingresses")]
        private InputList<Inputs.NetworkPolicyIngressGetArgs>? _ingresses;
        public InputList<Inputs.NetworkPolicyIngressGetArgs> Ingresses
        {
            get => _ingresses ?? (_ingresses = new InputList<Inputs.NetworkPolicyIngressGetArgs>());
            set => _ingresses = value;
        }

        [Input("instanceSelectors")]
        private InputList<Inputs.NetworkPolicyInstanceSelectorGetArgs>? _instanceSelectors;
        public InputList<Inputs.NetworkPolicyInstanceSelectorGetArgs> InstanceSelectors
        {
            get => _instanceSelectors ?? (_instanceSelectors = new InputList<Inputs.NetworkPolicyInstanceSelectorGetArgs>());
            set => _instanceSelectors = value;
        }

        [Input("labels")]
        private InputMap<string>? _labels;
        public InputMap<string> Labels
        {
            get => _labels ?? (_labels = new InputMap<string>());
            set => _labels = value;
        }

        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("networkSelectors")]
        private InputList<Inputs.NetworkPolicyNetworkSelectorGetArgs>? _networkSelectors;
        public InputList<Inputs.NetworkPolicyNetworkSelectorGetArgs> NetworkSelectors
        {
            get => _networkSelectors ?? (_networkSelectors = new InputList<Inputs.NetworkPolicyNetworkSelectorGetArgs>());
            set => _networkSelectors = value;
        }

        [Input("policyTypes")]
        private InputList<string>? _policyTypes;
        public InputList<string> PolicyTypes
        {
            get => _policyTypes ?? (_policyTypes = new InputList<string>());
            set => _policyTypes = value;
        }

        [Input("priority")]
        public Input<int>? Priority { get; set; }

        [Input("slug")]
        public Input<string>? Slug { get; set; }

        [Input("version")]
        public Input<string>? Version { get; set; }

        public NetworkPolicyState()
        {
        }
        public static new NetworkPolicyState Empty => new NetworkPolicyState();
    }
}
