# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_stackpath.compute as __compute
    compute = __compute
    import pulumi_stackpath.config as __config
    config = __config
    import pulumi_stackpath.storage as __storage
    storage = __storage
else:
    compute = _utilities.lazy_import('pulumi_stackpath.compute')
    config = _utilities.lazy_import('pulumi_stackpath.config')
    storage = _utilities.lazy_import('pulumi_stackpath.storage')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "stackpath",
  "mod": "compute/network",
  "fqn": "pulumi_stackpath.compute",
  "classes": {
   "stackpath:compute/network:Network": "Network"
  }
 },
 {
  "pkg": "stackpath",
  "mod": "compute/networkPolicy",
  "fqn": "pulumi_stackpath.compute",
  "classes": {
   "stackpath:compute/networkPolicy:NetworkPolicy": "NetworkPolicy"
  }
 },
 {
  "pkg": "stackpath",
  "mod": "compute/networkRoute",
  "fqn": "pulumi_stackpath.compute",
  "classes": {
   "stackpath:compute/networkRoute:NetworkRoute": "NetworkRoute"
  }
 },
 {
  "pkg": "stackpath",
  "mod": "compute/networkSubnet",
  "fqn": "pulumi_stackpath.compute",
  "classes": {
   "stackpath:compute/networkSubnet:NetworkSubnet": "NetworkSubnet"
  }
 },
 {
  "pkg": "stackpath",
  "mod": "compute/workload",
  "fqn": "pulumi_stackpath.compute",
  "classes": {
   "stackpath:compute/workload:Workload": "Workload"
  }
 },
 {
  "pkg": "stackpath",
  "mod": "storage/bucket",
  "fqn": "pulumi_stackpath.storage",
  "classes": {
   "stackpath:storage/bucket:Bucket": "Bucket"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "stackpath",
  "token": "pulumi:providers:stackpath",
  "fqn": "pulumi_stackpath",
  "class": "Provider"
 }
]
"""
)
