on:
  push:
    tags:
      - 'v*'
jobs:
  publish_binary:
     name: publish          
     runs-on: ubuntu-latest 
     steps:
     - name: Checkout Repo
       uses: actions/checkout@v2
     - name: Unshallow clone for tags
       run: git fetch --prune --unshallow --tags
     - name: Install Go
       uses: actions/setup-go@v2
       with:
         go-version: ${{matrix.goversion}}
     - name: Import GPG key
       id: import_gpg
       uses: paultyng/ghaction-import-gpg@v2.1.0
       env:
         GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
     - name: Install pulumictl
       uses: jaxxstorm/action-install-gh-release@v1.5.0
       with:
         repo: pulumi/pulumictl
     - name: Run GoReleaser
       uses: goreleaser/goreleaser-action@v2
       with:
         args: -p 3 release --rm-dist
         version: latest
       env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     strategy:
       fail-fast: true
       matrix:
         goversion:
         - 1.21.x

  publish_sdk:
    name: Publish SDKs
    runs-on: ubuntu-latest
    needs: publish_binary
    steps:
    - name: Publish SDKs
      uses: pulumi/pulumi-package-publisher@v0.0.13
    strategy:
      fail-fast: true
      matrix:
        language:
          - nodejs
        nodeversion:
          - 18.x
          - 20.x
          - 21.x
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
