on:
  push:
    tags:
      - 'v*'

jobs:
  publish_binary:
     name: publish          
     runs-on: ubuntu-latest 
     # Add write permissions for the GITHUB_TOKEN
     permissions: write-all
     steps:
     - name: Checkout Repo
       uses: actions/checkout@v4
       with:
         fetch-depth: 0
         fetch-tags: true
     - name: Install Go
       uses: actions/setup-go@v5
       with:
         go-version: ${{matrix.goversion}}
     - name: Install pulumictl
       uses: jaxxstorm/action-install-gh-release@v1
       with:
         repo: pulumi/pulumictl
     - name: Run GoReleaser
       uses: goreleaser/goreleaser-action@v5
       with:
         args: release --clean
         version: latest
     strategy:
       fail-fast: true
       matrix:
         goversion:
         - 1.21.x
     env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish_sdk:
    name: Publish SDKs
    runs-on: ubuntu-latest
    permissions: write-all
    needs: publish_binary
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true
    - name: Install pulumictl
      uses: jaxxstorm/action-install-gh-release@v1
      with:
        repo: pulumi/pulumictl
    - name: Install Pulumi CLI
      uses: pulumi/action-install-pulumi-cli@v2
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{matrix.nodeversion}}
        registry-url: ${{env.NPM_REGISTRY_URL}}
    - name: Build SDK
      run: make build_${{ matrix.language }}
    - name: Check worktree clean
      run: |
        git update-index -q --refresh
        if ! git diff-files --quiet; then
            >&2 echo "error: working tree is not clean, aborting!"
            git status
            git diff
            exit 1
        fi
    - if: ${{ matrix.language == 'nodejs' && env.PUBLISH_NPM == 'true' }}
      uses: JS-DevTools/npm-publish@v3
      with:
        access: "public"
        token: ${{ env.NPM_TOKEN }}
        package: ${{github.workspace}}/sdk/nodejs/bin/package.json
    strategy:
      fail-fast: true
      matrix:
        language:
          - nodejs
        nodeversion:
          - latest # For future-proofing
          - 21.x   # Latest at workflow creation
          - 20.x   # LTS release
          - 18.x   # Previous LTS release
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPMJS_API_TOKEN }}
      NODE_AUTH_TOKEN: ${{ secrets.NPMJS_API_TOKEN }}
      PUBLISH_NPM: true
      NPM_REGISTRY_URL: https://registry.npmjs.org
