# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities

import types

__config__ = pulumi.Config('stackpath')


class _ExportableConfig(types.ModuleType):
    @property
    def access_token(self) -> Optional[str]:
        return __config__.get('accessToken')

    @property
    def base_url(self) -> Optional[str]:
        return __config__.get('baseUrl')

    @property
    def client_id(self) -> Optional[str]:
        return __config__.get('clientId')

    @property
    def client_secret(self) -> Optional[str]:
        return __config__.get('clientSecret')

    @property
    def stack_id(self) -> Optional[str]:
        return __config__.get('stackId')

