// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackpath.Compute.Inputs
{

    public sealed class NetworkPolicyEgressToArgs : global::Pulumi.ResourceArgs
    {
        [Input("instanceSelectors")]
        private InputList<Inputs.NetworkPolicyEgressToInstanceSelectorArgs>? _instanceSelectors;
        public InputList<Inputs.NetworkPolicyEgressToInstanceSelectorArgs> InstanceSelectors
        {
            get => _instanceSelectors ?? (_instanceSelectors = new InputList<Inputs.NetworkPolicyEgressToInstanceSelectorArgs>());
            set => _instanceSelectors = value;
        }

        [Input("ipBlocks")]
        private InputList<Inputs.NetworkPolicyEgressToIpBlockArgs>? _ipBlocks;
        public InputList<Inputs.NetworkPolicyEgressToIpBlockArgs> IpBlocks
        {
            get => _ipBlocks ?? (_ipBlocks = new InputList<Inputs.NetworkPolicyEgressToIpBlockArgs>());
            set => _ipBlocks = value;
        }

        [Input("networkSelectors")]
        private InputList<Inputs.NetworkPolicyEgressToNetworkSelectorArgs>? _networkSelectors;
        public InputList<Inputs.NetworkPolicyEgressToNetworkSelectorArgs> NetworkSelectors
        {
            get => _networkSelectors ?? (_networkSelectors = new InputList<Inputs.NetworkPolicyEgressToNetworkSelectorArgs>());
            set => _networkSelectors = value;
        }

        public NetworkPolicyEgressToArgs()
        {
        }
        public static new NetworkPolicyEgressToArgs Empty => new NetworkPolicyEgressToArgs();
    }
}
