// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackpath.Compute.Inputs
{

    public sealed class NetworkPolicyEgressGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("action", required: true)]
        public Input<string> Action { get; set; } = null!;

        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("protocol")]
        public Input<Inputs.NetworkPolicyEgressProtocolGetArgs>? Protocol { get; set; }

        [Input("to")]
        public Input<Inputs.NetworkPolicyEgressToGetArgs>? To { get; set; }

        public NetworkPolicyEgressGetArgs()
        {
        }
        public static new NetworkPolicyEgressGetArgs Empty => new NetworkPolicyEgressGetArgs();
    }
}
