// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Stackpath.Stackpath.Compute.Inputs
{

    public sealed class NetworkPolicyEgressToIpBlockGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("cidr", required: true)]
        public Input<string> Cidr { get; set; } = null!;

        [Input("excepts")]
        private InputList<string>? _excepts;
        public InputList<string> Excepts
        {
            get => _excepts ?? (_excepts = new InputList<string>());
            set => _excepts = value;
        }

        public NetworkPolicyEgressToIpBlockGetArgs()
        {
        }
        public static new NetworkPolicyEgressToIpBlockGetArgs Empty => new NetworkPolicyEgressToIpBlockGetArgs();
    }
}
