// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackpath.Compute.Inputs
{

    public sealed class NetworkPolicyEgressProtocolGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("ah")]
        public Input<Inputs.NetworkPolicyEgressProtocolAhGetArgs>? Ah { get; set; }

        [Input("esp")]
        public Input<Inputs.NetworkPolicyEgressProtocolEspGetArgs>? Esp { get; set; }

        [Input("gre")]
        public Input<Inputs.NetworkPolicyEgressProtocolGreGetArgs>? Gre { get; set; }

        [Input("icmp")]
        public Input<Inputs.NetworkPolicyEgressProtocolIcmpGetArgs>? Icmp { get; set; }

        [Input("tcp")]
        public Input<Inputs.NetworkPolicyEgressProtocolTcpGetArgs>? Tcp { get; set; }

        [Input("tcpUdp")]
        public Input<Inputs.NetworkPolicyEgressProtocolTcpUdpGetArgs>? TcpUdp { get; set; }

        [Input("udp")]
        public Input<Inputs.NetworkPolicyEgressProtocolUdpGetArgs>? Udp { get; set; }

        public NetworkPolicyEgressProtocolGetArgs()
        {
        }
        public static new NetworkPolicyEgressProtocolGetArgs Empty => new NetworkPolicyEgressProtocolGetArgs();
    }
}
