// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackpath.Compute.Inputs
{

    public sealed class NetworkPolicyIngressArgs : global::Pulumi.ResourceArgs
    {
        [Input("action", required: true)]
        public Input<string> Action { get; set; } = null!;

        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("from")]
        public Input<Inputs.NetworkPolicyIngressFromArgs>? From { get; set; }

        [Input("protocol")]
        public Input<Inputs.NetworkPolicyIngressProtocolArgs>? Protocol { get; set; }

        public NetworkPolicyIngressArgs()
        {
        }
        public static new NetworkPolicyIngressArgs Empty => new NetworkPolicyIngressArgs();
    }
}
