// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackpath.Compute.Inputs
{

    public sealed class NetworkPolicyEgressProtocolArgs : global::Pulumi.ResourceArgs
    {
        [Input("ah")]
        public Input<Inputs.NetworkPolicyEgressProtocolAhArgs>? Ah { get; set; }

        [Input("esp")]
        public Input<Inputs.NetworkPolicyEgressProtocolEspArgs>? Esp { get; set; }

        [Input("gre")]
        public Input<Inputs.NetworkPolicyEgressProtocolGreArgs>? Gre { get; set; }

        [Input("icmp")]
        public Input<Inputs.NetworkPolicyEgressProtocolIcmpArgs>? Icmp { get; set; }

        [Input("tcp")]
        public Input<Inputs.NetworkPolicyEgressProtocolTcpArgs>? Tcp { get; set; }

        [Input("tcpUdp")]
        public Input<Inputs.NetworkPolicyEgressProtocolTcpUdpArgs>? TcpUdp { get; set; }

        [Input("udp")]
        public Input<Inputs.NetworkPolicyEgressProtocolUdpArgs>? Udp { get; set; }

        public NetworkPolicyEgressProtocolArgs()
        {
        }
        public static new NetworkPolicyEgressProtocolArgs Empty => new NetworkPolicyEgressProtocolArgs();
    }
}
