// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackpath.Compute.Inputs
{

    public sealed class NetworkPolicyEgressToGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("instanceSelectors")]
        private InputList<Inputs.NetworkPolicyEgressToInstanceSelectorGetArgs>? _instanceSelectors;
        public InputList<Inputs.NetworkPolicyEgressToInstanceSelectorGetArgs> InstanceSelectors
        {
            get => _instanceSelectors ?? (_instanceSelectors = new InputList<Inputs.NetworkPolicyEgressToInstanceSelectorGetArgs>());
            set => _instanceSelectors = value;
        }

        [Input("ipBlocks")]
        private InputList<Inputs.NetworkPolicyEgressToIpBlockGetArgs>? _ipBlocks;
        public InputList<Inputs.NetworkPolicyEgressToIpBlockGetArgs> IpBlocks
        {
            get => _ipBlocks ?? (_ipBlocks = new InputList<Inputs.NetworkPolicyEgressToIpBlockGetArgs>());
            set => _ipBlocks = value;
        }

        [Input("networkSelectors")]
        private InputList<Inputs.NetworkPolicyEgressToNetworkSelectorGetArgs>? _networkSelectors;
        public InputList<Inputs.NetworkPolicyEgressToNetworkSelectorGetArgs> NetworkSelectors
        {
            get => _networkSelectors ?? (_networkSelectors = new InputList<Inputs.NetworkPolicyEgressToNetworkSelectorGetArgs>());
            set => _networkSelectors = value;
        }

        public NetworkPolicyEgressToGetArgs()
        {
        }
        public static new NetworkPolicyEgressToGetArgs Empty => new NetworkPolicyEgressToGetArgs();
    }
}
