// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Stackpath.Stackpath.Compute.Inputs
{

    public sealed class WorkloadVolumeClaimResourcesArgs : global::Pulumi.ResourceArgs
    {
        [Input("requests", required: true)]
        private InputMap<string>? _requests;
        public InputMap<string> Requests
        {
            get => _requests ?? (_requests = new InputMap<string>());
            set => _requests = value;
        }

        public WorkloadVolumeClaimResourcesArgs()
        {
        }
        public static new WorkloadVolumeClaimResourcesArgs Empty => new WorkloadVolumeClaimResourcesArgs();
    }
}
