// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Stackpath.Stackpath.Compute.Inputs
{

    public sealed class WorkloadImagePullCredentialDockerRegistryArgs : global::Pulumi.ResourceArgs
    {
        [Input("email")]
        private Input<string>? _email;
        public Input<string>? Email
        {
            get => _email;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _email = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("password", required: true)]
        private Input<string>? _password;
        public Input<string>? Password
        {
            get => _password;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _password = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("server")]
        public Input<string>? Server { get; set; }

        [Input("username", required: true)]
        public Input<string> Username { get; set; } = null!;

        public WorkloadImagePullCredentialDockerRegistryArgs()
        {
        }
        public static new WorkloadImagePullCredentialDockerRegistryArgs Empty => new WorkloadImagePullCredentialDockerRegistryArgs();
    }
}
