// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Stackpath.Stackpath.Compute.Inputs
{

    public sealed class WorkloadInstanceContainerEnvValueFromArgs : global::Pulumi.ResourceArgs
    {
        [Input("instanceFieldRef")]
        public Input<Inputs.WorkloadInstanceContainerEnvValueFromInstanceFieldRefArgs>? InstanceFieldRef { get; set; }

        public WorkloadInstanceContainerEnvValueFromArgs()
        {
        }
        public static new WorkloadInstanceContainerEnvValueFromArgs Empty => new WorkloadInstanceContainerEnvValueFromArgs();
    }
}
