// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackpath.Compute.Inputs
{

    public sealed class WorkloadTargetScaleSettingsArgs : global::Pulumi.ResourceArgs
    {
        [Input("metrics", required: true)]
        private InputList<Inputs.WorkloadTargetScaleSettingsMetricArgs>? _metrics;
        public InputList<Inputs.WorkloadTargetScaleSettingsMetricArgs> Metrics
        {
            get => _metrics ?? (_metrics = new InputList<Inputs.WorkloadTargetScaleSettingsMetricArgs>());
            set => _metrics = value;
        }

        public WorkloadTargetScaleSettingsArgs()
        {
        }
        public static new WorkloadTargetScaleSettingsArgs Empty => new WorkloadTargetScaleSettingsArgs();
    }
}
