// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Stackpath.Stackpath.Compute.Inputs
{

    public sealed class WorkloadVirtualMachineRuntimeEnvironmentDnsArgs : global::Pulumi.ResourceArgs
    {
        [Input("hostAliases")]
        private InputList<Inputs.WorkloadVirtualMachineRuntimeEnvironmentDnsHostAliasArgs>? _hostAliases;
        public InputList<Inputs.WorkloadVirtualMachineRuntimeEnvironmentDnsHostAliasArgs> HostAliases
        {
            get => _hostAliases ?? (_hostAliases = new InputList<Inputs.WorkloadVirtualMachineRuntimeEnvironmentDnsHostAliasArgs>());
            set => _hostAliases = value;
        }

        [Input("resolverConfigs")]
        private InputList<Inputs.WorkloadVirtualMachineRuntimeEnvironmentDnsResolverConfigArgs>? _resolverConfigs;
        public InputList<Inputs.WorkloadVirtualMachineRuntimeEnvironmentDnsResolverConfigArgs> ResolverConfigs
        {
            get => _resolverConfigs ?? (_resolverConfigs = new InputList<Inputs.WorkloadVirtualMachineRuntimeEnvironmentDnsResolverConfigArgs>());
            set => _resolverConfigs = value;
        }

        public WorkloadVirtualMachineRuntimeEnvironmentDnsArgs()
        {
        }
        public static new WorkloadVirtualMachineRuntimeEnvironmentDnsArgs Empty => new WorkloadVirtualMachineRuntimeEnvironmentDnsArgs();
    }
}
