// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackpath.Compute.Inputs
{

    public sealed class WorkloadInstanceGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("containers")]
        private InputList<Inputs.WorkloadInstanceContainerGetArgs>? _containers;
        public InputList<Inputs.WorkloadInstanceContainerGetArgs> Containers
        {
            get => _containers ?? (_containers = new InputList<Inputs.WorkloadInstanceContainerGetArgs>());
            set => _containers = value;
        }

        [Input("externalIpAddress")]
        public Input<string>? ExternalIpAddress { get; set; }

        [Input("ipAddress")]
        public Input<string>? IpAddress { get; set; }

        [Input("location")]
        public Input<Inputs.WorkloadInstanceLocationGetArgs>? Location { get; set; }

        [Input("message")]
        public Input<string>? Message { get; set; }

        [Input("metadata")]
        public Input<Inputs.WorkloadInstanceMetadataGetArgs>? Metadata { get; set; }

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("networkInterfaces")]
        private InputList<Inputs.WorkloadInstanceNetworkInterfaceGetArgs>? _networkInterfaces;
        public InputList<Inputs.WorkloadInstanceNetworkInterfaceGetArgs> NetworkInterfaces
        {
            get => _networkInterfaces ?? (_networkInterfaces = new InputList<Inputs.WorkloadInstanceNetworkInterfaceGetArgs>());
            set => _networkInterfaces = value;
        }

        [Input("phase")]
        public Input<string>? Phase { get; set; }

        [Input("reason")]
        public Input<string>? Reason { get; set; }

        [Input("virtualMachine")]
        public Input<Inputs.WorkloadInstanceVirtualMachineGetArgs>? VirtualMachine { get; set; }

        public WorkloadInstanceGetArgs()
        {
        }
        public static new WorkloadInstanceGetArgs Empty => new WorkloadInstanceGetArgs();
    }
}
