// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Stackpath.Stackpath.Compute.Inputs
{

    public sealed class WorkloadContainerRuntimeEnvironmentDnsResolverConfigGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("nameservers")]
        private InputList<string>? _nameservers;
        public InputList<string> Nameservers
        {
            get => _nameservers ?? (_nameservers = new InputList<string>());
            set => _nameservers = value;
        }

        [Input("options")]
        private InputMap<object>? _options;
        public InputMap<object> Options
        {
            get => _options ?? (_options = new InputMap<object>());
            set => _options = value;
        }

        [Input("searches")]
        private InputList<string>? _searches;
        public InputList<string> Searches
        {
            get => _searches ?? (_searches = new InputList<string>());
            set => _searches = value;
        }

        public WorkloadContainerRuntimeEnvironmentDnsResolverConfigGetArgs()
        {
        }
        public static new WorkloadContainerRuntimeEnvironmentDnsResolverConfigGetArgs Empty => new WorkloadContainerRuntimeEnvironmentDnsResolverConfigGetArgs();
    }
}
