// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackpath.Compute.Inputs
{

    public sealed class WorkloadContainerGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("commands")]
        private InputList<string>? _commands;
        public InputList<string> Commands
        {
            get => _commands ?? (_commands = new InputList<string>());
            set => _commands = value;
        }

        [Input("envs")]
        private InputList<Inputs.WorkloadContainerEnvGetArgs>? _envs;
        public InputList<Inputs.WorkloadContainerEnvGetArgs> Envs
        {
            get => _envs ?? (_envs = new InputList<Inputs.WorkloadContainerEnvGetArgs>());
            set => _envs = value;
        }

        [Input("image", required: true)]
        public Input<string> Image { get; set; } = null!;

        [Input("livenessProbe")]
        public Input<Inputs.WorkloadContainerLivenessProbeGetArgs>? LivenessProbe { get; set; }

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("ports")]
        private InputList<Inputs.WorkloadContainerPortGetArgs>? _ports;
        public InputList<Inputs.WorkloadContainerPortGetArgs> Ports
        {
            get => _ports ?? (_ports = new InputList<Inputs.WorkloadContainerPortGetArgs>());
            set => _ports = value;
        }

        [Input("readinessProbe")]
        public Input<Inputs.WorkloadContainerReadinessProbeGetArgs>? ReadinessProbe { get; set; }

        [Input("resources", required: true)]
        public Input<Inputs.WorkloadContainerResourcesGetArgs> Resources { get; set; } = null!;

        [Input("volumeMounts")]
        private InputList<Inputs.WorkloadContainerVolumeMountGetArgs>? _volumeMounts;
        public InputList<Inputs.WorkloadContainerVolumeMountGetArgs> VolumeMounts
        {
            get => _volumeMounts ?? (_volumeMounts = new InputList<Inputs.WorkloadContainerVolumeMountGetArgs>());
            set => _volumeMounts = value;
        }

        public WorkloadContainerGetArgs()
        {
        }
        public static new WorkloadContainerGetArgs Empty => new WorkloadContainerGetArgs();
    }
}
