// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Stackpath.Stackpath.Compute.Inputs
{

    public sealed class WorkloadImagePullCredentialGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("dockerRegistry", required: true)]
        public Input<Inputs.WorkloadImagePullCredentialDockerRegistryGetArgs> DockerRegistry { get; set; } = null!;

        public WorkloadImagePullCredentialGetArgs()
        {
        }
        public static new WorkloadImagePullCredentialGetArgs Empty => new WorkloadImagePullCredentialGetArgs();
    }
}
