// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Stackpath.Stackpath.Compute.Inputs
{

    public sealed class WorkloadContainerRuntimeEnvironmentDnsArgs : global::Pulumi.ResourceArgs
    {
        [Input("hostAliases")]
        private InputList<Inputs.WorkloadContainerRuntimeEnvironmentDnsHostAliasArgs>? _hostAliases;
        public InputList<Inputs.WorkloadContainerRuntimeEnvironmentDnsHostAliasArgs> HostAliases
        {
            get => _hostAliases ?? (_hostAliases = new InputList<Inputs.WorkloadContainerRuntimeEnvironmentDnsHostAliasArgs>());
            set => _hostAliases = value;
        }

        [Input("resolverConfigs")]
        private InputList<Inputs.WorkloadContainerRuntimeEnvironmentDnsResolverConfigArgs>? _resolverConfigs;
        public InputList<Inputs.WorkloadContainerRuntimeEnvironmentDnsResolverConfigArgs> ResolverConfigs
        {
            get => _resolverConfigs ?? (_resolverConfigs = new InputList<Inputs.WorkloadContainerRuntimeEnvironmentDnsResolverConfigArgs>());
            set => _resolverConfigs = value;
        }

        public WorkloadContainerRuntimeEnvironmentDnsArgs()
        {
        }
        public static new WorkloadContainerRuntimeEnvironmentDnsArgs Empty => new WorkloadContainerRuntimeEnvironmentDnsArgs();
    }
}
