// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Stackpath.Stackpath.Compute.Inputs
{

    public sealed class WorkloadInitContainerEnvArgs : global::Pulumi.ResourceArgs
    {
        [Input("key", required: true)]
        public Input<string> Key { get; set; } = null!;

        [Input("secretValue")]
        private Input<string>? _secretValue;
        public Input<string>? SecretValue
        {
            get => _secretValue;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _secretValue = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("value")]
        public Input<string>? Value { get; set; }

        [Input("valueFrom")]
        public Input<Inputs.WorkloadInitContainerEnvValueFromArgs>? ValueFrom { get; set; }

        public WorkloadInitContainerEnvArgs()
        {
        }
        public static new WorkloadInitContainerEnvArgs Empty => new WorkloadInitContainerEnvArgs();
    }
}
