// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Stackpath.Stackpath.Compute.Inputs
{

    public sealed class WorkloadInstanceNetworkInterfaceArgs : global::Pulumi.ResourceArgs
    {
        [Input("gateway", required: true)]
        public Input<string> Gateway { get; set; } = null!;

        [Input("ipAddress", required: true)]
        public Input<string> IpAddress { get; set; } = null!;

        [Input("ipAddressAliases")]
        private InputList<string>? _ipAddressAliases;
        public InputList<string> IpAddressAliases
        {
            get => _ipAddressAliases ?? (_ipAddressAliases = new InputList<string>());
            set => _ipAddressAliases = value;
        }

        [Input("ipv6Address", required: true)]
        public Input<string> Ipv6Address { get; set; } = null!;

        [Input("ipv6AddressAliases")]
        private InputList<string>? _ipv6AddressAliases;
        public InputList<string> Ipv6AddressAliases
        {
            get => _ipv6AddressAliases ?? (_ipv6AddressAliases = new InputList<string>());
            set => _ipv6AddressAliases = value;
        }

        [Input("ipv6Gateway", required: true)]
        public Input<string> Ipv6Gateway { get; set; } = null!;

        [Input("network", required: true)]
        public Input<string> Network { get; set; } = null!;

        public WorkloadInstanceNetworkInterfaceArgs()
        {
        }
        public static new WorkloadInstanceNetworkInterfaceArgs Empty => new WorkloadInstanceNetworkInterfaceArgs();
    }
}
