// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackpath.Compute.Inputs
{

    public sealed class WorkloadInstanceVirtualMachineGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("image", required: true)]
        public Input<string> Image { get; set; } = null!;

        [Input("livenessProbe")]
        public Input<Inputs.WorkloadInstanceVirtualMachineLivenessProbeGetArgs>? LivenessProbe { get; set; }

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("ports")]
        private InputList<Inputs.WorkloadInstanceVirtualMachinePortGetArgs>? _ports;
        public InputList<Inputs.WorkloadInstanceVirtualMachinePortGetArgs> Ports
        {
            get => _ports ?? (_ports = new InputList<Inputs.WorkloadInstanceVirtualMachinePortGetArgs>());
            set => _ports = value;
        }

        [Input("readinessProbe")]
        public Input<Inputs.WorkloadInstanceVirtualMachineReadinessProbeGetArgs>? ReadinessProbe { get; set; }

        [Input("resources", required: true)]
        public Input<Inputs.WorkloadInstanceVirtualMachineResourcesGetArgs> Resources { get; set; } = null!;

        [Input("userData")]
        public Input<string>? UserData { get; set; }

        [Input("volumeMounts")]
        private InputList<Inputs.WorkloadInstanceVirtualMachineVolumeMountGetArgs>? _volumeMounts;
        public InputList<Inputs.WorkloadInstanceVirtualMachineVolumeMountGetArgs> VolumeMounts
        {
            get => _volumeMounts ?? (_volumeMounts = new InputList<Inputs.WorkloadInstanceVirtualMachineVolumeMountGetArgs>());
            set => _volumeMounts = value;
        }

        public WorkloadInstanceVirtualMachineGetArgs()
        {
        }
        public static new WorkloadInstanceVirtualMachineGetArgs Empty => new WorkloadInstanceVirtualMachineGetArgs();
    }
}
