// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackpath.Compute.Inputs
{

    public sealed class WorkloadContainerArgs : global::Pulumi.ResourceArgs
    {
        [Input("commands")]
        private InputList<string>? _commands;
        public InputList<string> Commands
        {
            get => _commands ?? (_commands = new InputList<string>());
            set => _commands = value;
        }

        [Input("envs")]
        private InputList<Inputs.WorkloadContainerEnvArgs>? _envs;
        public InputList<Inputs.WorkloadContainerEnvArgs> Envs
        {
            get => _envs ?? (_envs = new InputList<Inputs.WorkloadContainerEnvArgs>());
            set => _envs = value;
        }

        [Input("image", required: true)]
        public Input<string> Image { get; set; } = null!;

        [Input("livenessProbe")]
        public Input<Inputs.WorkloadContainerLivenessProbeArgs>? LivenessProbe { get; set; }

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("ports")]
        private InputList<Inputs.WorkloadContainerPortArgs>? _ports;
        public InputList<Inputs.WorkloadContainerPortArgs> Ports
        {
            get => _ports ?? (_ports = new InputList<Inputs.WorkloadContainerPortArgs>());
            set => _ports = value;
        }

        [Input("readinessProbe")]
        public Input<Inputs.WorkloadContainerReadinessProbeArgs>? ReadinessProbe { get; set; }

        [Input("resources", required: true)]
        public Input<Inputs.WorkloadContainerResourcesArgs> Resources { get; set; } = null!;

        [Input("volumeMounts")]
        private InputList<Inputs.WorkloadContainerVolumeMountArgs>? _volumeMounts;
        public InputList<Inputs.WorkloadContainerVolumeMountArgs> VolumeMounts
        {
            get => _volumeMounts ?? (_volumeMounts = new InputList<Inputs.WorkloadContainerVolumeMountArgs>());
            set => _volumeMounts = value;
        }

        public WorkloadContainerArgs()
        {
        }
        public static new WorkloadContainerArgs Empty => new WorkloadContainerArgs();
    }
}
