// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackpath.Compute.Inputs
{

    public sealed class WorkloadInstanceVirtualMachineArgs : global::Pulumi.ResourceArgs
    {
        [Input("image", required: true)]
        public Input<string> Image { get; set; } = null!;

        [Input("livenessProbe")]
        public Input<Inputs.WorkloadInstanceVirtualMachineLivenessProbeArgs>? LivenessProbe { get; set; }

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("ports")]
        private InputList<Inputs.WorkloadInstanceVirtualMachinePortArgs>? _ports;
        public InputList<Inputs.WorkloadInstanceVirtualMachinePortArgs> Ports
        {
            get => _ports ?? (_ports = new InputList<Inputs.WorkloadInstanceVirtualMachinePortArgs>());
            set => _ports = value;
        }

        [Input("readinessProbe")]
        public Input<Inputs.WorkloadInstanceVirtualMachineReadinessProbeArgs>? ReadinessProbe { get; set; }

        [Input("resources", required: true)]
        public Input<Inputs.WorkloadInstanceVirtualMachineResourcesArgs> Resources { get; set; } = null!;

        [Input("userData")]
        public Input<string>? UserData { get; set; }

        [Input("volumeMounts")]
        private InputList<Inputs.WorkloadInstanceVirtualMachineVolumeMountArgs>? _volumeMounts;
        public InputList<Inputs.WorkloadInstanceVirtualMachineVolumeMountArgs> VolumeMounts
        {
            get => _volumeMounts ?? (_volumeMounts = new InputList<Inputs.WorkloadInstanceVirtualMachineVolumeMountArgs>());
            set => _volumeMounts = value;
        }

        public WorkloadInstanceVirtualMachineArgs()
        {
        }
        public static new WorkloadInstanceVirtualMachineArgs Empty => new WorkloadInstanceVirtualMachineArgs();
    }
}
