// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Stackpath.Stackpath.Compute.Inputs
{

    public sealed class WorkloadInitContainerArgs : global::Pulumi.ResourceArgs
    {
        [Input("args")]
        private InputList<string>? _args;
        public InputList<string> Args
        {
            get => _args ?? (_args = new InputList<string>());
            set => _args = value;
        }

        [Input("commands")]
        private InputList<string>? _commands;
        public InputList<string> Commands
        {
            get => _commands ?? (_commands = new InputList<string>());
            set => _commands = value;
        }

        [Input("envs")]
        private InputList<Inputs.WorkloadInitContainerEnvArgs>? _envs;
        public InputList<Inputs.WorkloadInitContainerEnvArgs> Envs
        {
            get => _envs ?? (_envs = new InputList<Inputs.WorkloadInitContainerEnvArgs>());
            set => _envs = value;
        }

        [Input("image", required: true)]
        public Input<string> Image { get; set; } = null!;

        [Input("livenessProbe")]
        public Input<Inputs.WorkloadInitContainerLivenessProbeArgs>? LivenessProbe { get; set; }

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("ports")]
        private InputList<Inputs.WorkloadInitContainerPortArgs>? _ports;
        public InputList<Inputs.WorkloadInitContainerPortArgs> Ports
        {
            get => _ports ?? (_ports = new InputList<Inputs.WorkloadInitContainerPortArgs>());
            set => _ports = value;
        }

        [Input("readinessProbe")]
        public Input<Inputs.WorkloadInitContainerReadinessProbeArgs>? ReadinessProbe { get; set; }

        [Input("resources", required: true)]
        public Input<Inputs.WorkloadInitContainerResourcesArgs> Resources { get; set; } = null!;

        [Input("securityContext")]
        public Input<Inputs.WorkloadInitContainerSecurityContextArgs>? SecurityContext { get; set; }

        [Input("volumeMounts")]
        private InputList<Inputs.WorkloadInitContainerVolumeMountArgs>? _volumeMounts;
        public InputList<Inputs.WorkloadInitContainerVolumeMountArgs> VolumeMounts
        {
            get => _volumeMounts ?? (_volumeMounts = new InputList<Inputs.WorkloadInitContainerVolumeMountArgs>());
            set => _volumeMounts = value;
        }

        public WorkloadInitContainerArgs()
        {
        }
        public static new WorkloadInitContainerArgs Empty => new WorkloadInitContainerArgs();
    }
}
