// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Stackpath.Stackpath.Compute.Inputs
{

    public sealed class WorkloadContainerRuntimeEnvironmentGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("dns", required: true)]
        public Input<Inputs.WorkloadContainerRuntimeEnvironmentDnsGetArgs> Dns { get; set; } = null!;

        [Input("securityContext")]
        public Input<Inputs.WorkloadContainerRuntimeEnvironmentSecurityContextGetArgs>? SecurityContext { get; set; }

        [Input("shareProcessNamespace")]
        public Input<bool>? ShareProcessNamespace { get; set; }

        [Input("terminationGracePeriodSeconds")]
        public Input<int>? TerminationGracePeriodSeconds { get; set; }

        public WorkloadContainerRuntimeEnvironmentGetArgs()
        {
        }
        public static new WorkloadContainerRuntimeEnvironmentGetArgs Empty => new WorkloadContainerRuntimeEnvironmentGetArgs();
    }
}
