// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackpath.Compute.Inputs
{

    public sealed class WorkloadInstanceNetworkInterfaceArgs : global::Pulumi.ResourceArgs
    {
        [Input("gateway", required: true)]
        public Input<string> Gateway { get; set; } = null!;

        [Input("ipAddress", required: true)]
        public Input<string> IpAddress { get; set; } = null!;

        [Input("ipAddressAliases")]
        private InputList<string>? _ipAddressAliases;
        public InputList<string> IpAddressAliases
        {
            get => _ipAddressAliases ?? (_ipAddressAliases = new InputList<string>());
            set => _ipAddressAliases = value;
        }

        [Input("network", required: true)]
        public Input<string> Network { get; set; } = null!;

        public WorkloadInstanceNetworkInterfaceArgs()
        {
        }
        public static new WorkloadInstanceNetworkInterfaceArgs Empty => new WorkloadInstanceNetworkInterfaceArgs();
    }
}
