// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Stackpath.Compute.Inputs
{

    public sealed class WorkloadTargetScaleSettingsGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("metrics", required: true)]
        private InputList<Inputs.WorkloadTargetScaleSettingsMetricGetArgs>? _metrics;
        public InputList<Inputs.WorkloadTargetScaleSettingsMetricGetArgs> Metrics
        {
            get => _metrics ?? (_metrics = new InputList<Inputs.WorkloadTargetScaleSettingsMetricGetArgs>());
            set => _metrics = value;
        }

        public WorkloadTargetScaleSettingsGetArgs()
        {
        }
        public static new WorkloadTargetScaleSettingsGetArgs Empty => new WorkloadTargetScaleSettingsGetArgs();
    }
}
