// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Stackpath.Stackpath.Compute.Inputs
{

    public sealed class WorkloadContainerRuntimeEnvironmentSecurityContextArgs : global::Pulumi.ResourceArgs
    {
        [Input("runAsGroup")]
        public Input<string>? RunAsGroup { get; set; }

        [Input("runAsNonRoot")]
        public Input<bool>? RunAsNonRoot { get; set; }

        [Input("runAsUser")]
        public Input<string>? RunAsUser { get; set; }

        [Input("supplementalGroups")]
        private InputList<string>? _supplementalGroups;
        public InputList<string> SupplementalGroups
        {
            get => _supplementalGroups ?? (_supplementalGroups = new InputList<string>());
            set => _supplementalGroups = value;
        }

        [Input("sysctl")]
        private InputMap<string>? _sysctl;
        public InputMap<string> Sysctl
        {
            get => _sysctl ?? (_sysctl = new InputMap<string>());
            set => _sysctl = value;
        }

        public WorkloadContainerRuntimeEnvironmentSecurityContextArgs()
        {
        }
        public static new WorkloadContainerRuntimeEnvironmentSecurityContextArgs Empty => new WorkloadContainerRuntimeEnvironmentSecurityContextArgs();
    }
}
